export default Object.freeze({
  DRAW_CIRCLE: 'DRAW_CIRCLE',
  DRAW_ELLIPSE: 'DRAW_ELLIPSE',
  DRAW_RECT: 'DRAW_RECT',
  DRAW_LINE: 'DRAW_LINE',
  DRAW_POLYLINE: 'DRAW_POLYLINE',
  DRAW_POLYGON: 'DRAW_POLYGON',
  DRAW_PATH: 'DRAW_PATH',
})
